const CLUBS = [
  "1.SFC Selb","1.TFC Aktivist Bergen 74","A.S. Cosenza","A.S.M. Nola 74","AC Los Remedios FM",
  "Achaioi TSC","Adachi TFC","Adelaide Subbuteo Table Football Club","Adrastians","AFT Turia 1981",
  "AJ Amiénois FT","ALC Wattrelos - Subbuteo Lille Metropole","Alliance française d'Odessa",
  "Argonautes Volou TSC","AS Iluro Futbol Taula","AS Subbuteo Club Potenza","ASAKUSA ZOO TFC",
  "ASCT Sessana 1982","Asd Alba Subbuteo Roma","Asd Ct Aosta Warriors","ASD SC Salernitana",
  "ASD Siracusa Calcio Tavolo","ASD Triestina Subbuteo","ASD Union Kroton 1988","ASD Volterrana 2016",
  "ASD VT CTS Fidenza","Associação Atlética Banco do Brasil - Caruaru","Athinaikos CS","Atlas FTC",
  "Atletico Pisa","Avenir Subbuteo Hennuyer","Azure Tokyo","Azzurra 99 Napoli","Bangu Atlético Clube",
  "Barcelona FT","BARI TABLE SOCCER","BCLF CRUC Cosenza","Belfast Barbarians",
  "Birmingham & District Table Soccer League","Blade TSC","Boise USL 95","Bologna Tigers Subbuteo",
  "Bormla SC","Borussia Bergkamen","BOSS","Botafogo de Futebol e Regatas","Boucle de la Seine Subbutéo",
  "Boudica Subbuteo Table Football Club","Brisbane Subbuteo Club","Bristol SC","Bruzia D086",
  "BSC Schwalbach","Bulldogs Vicenza","Calgary SC","California TSC","CAP Ciudad de Murcia FM",
  "Cape Town City Subbuteo Club","Cardiff Bluebirds TFC","Carolina TSC","CC Condors TSC","CCM Livorno",
  "CCT Eagles Napoli","CCT Roma","CD Olivais Moscavide","Celtic Combourg CFT","Central Victoria TFC",
  "CF os Belenenses","CF Sassoeiros","CFM Manolo Preciado","CFT Montivilliers","Charilaos Trikoupis TS",
  "CHASERS (Chadwell Heath & South Essex, Romford Subbuteo) Club","Chattanooga SL","Chesterfield TFC",
  "Cisplatina Futebol Clube","Club de Regatas Vasco da Gama","Club Stéphanois Subbuteo - ALC",
  "Colombo Sport Club","Colorado SC","Cov and Warks Subbuteo","Crimson Horses","CS Firenze",
  "CS Montréal","CS SC Serenissima Mestre","CS Solvay Vada","CS Virtus Rieti","CS Zarco","CT Paola",
  "CT Torino 2009","CT Versilia 2002","CTS Versilia Football Planet","Czech Subbuteo Team 2014",
  "Derry City","Doncaster Subbuteo Club","Dragonrose Subbuteo Club","Dundee United TFC",
  "DuPage County Table Soccer Club","Dutch Legends","Eagles II","Eagles Supporters Subbuteo",
  "Eastern Elias SC","Easterns Table Football Club","Elan Subbutéo Club de Champs-sur-Marne",
  "ELM'Aye SC","Elstow Lions TFC","Essener SC","ETS Subbuteo Club","Eurofighter Bochum",
  "Europa FC TSC","Evia CAN","F.lli Bari Reggio Emilia","Famagusta TFC","FantasyIncantum ASD",
  "Fides Livorno","Flaming Flickers SC","Florida Sharks TSC","FM La Plazoleta","Foggia CT",
  "Football de table de Pegomas","FTC Caen","FTC Saint-Symphorien-sur-Coise","Fukushima Table Football Club",
  "GCT DLF Gorizia","GD Bairro Novo","Glasgow TSA","Gliding Stars Aachen","Glyfada United TSC",
  "Godiva Subbuteo Club","Golazzo SC","Grand Rapids TSC","Granducato Subbuteo","GRAVURE TOKYO",
  "GRD 1º Maio Tires","Grifo Sombrero","GSC De Hyacinth","Guebwiller Alsace Subbuteo Club",
  "H'Attard SC","Hamilton SC","Harrow Hawks TSC","Haverhill Rovers tfc","Highlanders TSC",
  "Hipfingerz Subbuteo Club","Hobart Table Football Club","Hot Club d'Ecosse","Il Picchio Ascoli",
  "Irish Premier League","Irreal Nieder-Mörlen","JSC Rochefort","Jurong Central SC","Kansas City SC",
  "Kebun Bahru TFC","Kent Invicta TFC","Kettering Flicking Marvellous","Kirkstall Crusaders Subbuteo Club",
  "Knighton","Kragerø BFK","Lakhta Subbuteo TFC","Langton Green Subbuteo Club","Larissa TFC",
  "Lega Subbuteo Liga Odense","Leicester Foxes Subbuteo Club","Les Ducs Chalon-sur-Saône FTSC",
  "Lincoln Flickers SC","Linth Sliders SC","Liverpool TSC","London & Essex United",
  "London Road Subbuteo TSC","London Subbuteo Club","London TFC","Lone Star SL","Magic Team Tournai",
  "Mallorca Águilas FM","MARADONA TOKYO","Maremma Subbuteo","Maryland SC","Master Sanremo",
  "Mavericks Manawatu Subbuteo Club","Melbourne TFC","Merseyside SC","Messina Table Soccer",
  "Milton Keynes","Minimannia Aachen","Moralzarzal Subbuteo CAD","Mt. Hebron TSC",
  "Mulhouse Subbuteo by ASPTT","MVV Rijnmond","Myrmidones TSC","Nicosia Strikers","Noctuas Athens TSC",
  "North Shields STF","Northern California SC","Northern Falcons TFC","Northern Line Flickers TFC",
  "Northern Phoenix TFC","Old Lions Macerata","Old Sods Old Subbuteo Club","Olympia CS","ON T.S.C.",
  "OS Academy 1947","Osaka TFC","OSC Yamato Wild Blue TFC","Outer Banks SC","Palermo Subbuteo",
  "Panorama 1978 SC","Papata Group Ponticino","Paris Université Club","PB Subbuteo Fidenza",
  "Pedmore S&TFC","Pinco Devils Table Soccer","Piraeus Lions TSC","Piraeus Tigers TSC",
  "Pisani all'Uscio","Poitou Football de Table Club","Polis Athlitikos Syllogos Daskaliou Kerateas",
  "Proteas Athens SC","Racing White Woluwé Subbuteo","RAS (Rochford & Southend) Casual Subbuteo Club",
  "RC Lorraine Subbuteo Club","Rebels Genova","Rhegion Calabria","Rochefort TS",
  "Roligans Ilioupolis TSC","SAITAMA MARINES","São Paulo Futebol Clube","SB Komet Frankfurt",
  "SC Ascoli","SC Bad Sobernheim","SC Bagheria","SC Barakaldo","SC Bari","SC Berlin","SC Biella 91",
  "SC Cagliari","SC Castelfiorentino","SC Catania 1987","SC Charleroi","SC Connecticut",
  "SC Dragons Hong Kong","SC Fiamme Azzurre","SC Flanders","SC Fonte Nuova","SC Germania Schwerte 76",
  "SC Kickers 69 Offenbach","SC Ligures","SC Lion's Eugies","SC München 2014","SC Palermo 2016",
  "SC Pantere Lucca","SC Reeds","SC Samb","SC Sombrero","SC Stradivari Cremona","SC Temploux",
  "SC UD Santa María FM","SC Wallisellen","SC Weimar Wanderers","Scarlet Battalion SC","SCN Idstein",
  "Seattle SC","Section Subbutéo Squadra omessinca","SF SW gemaba Hitdorf","SG '94 Hannover",
  "SG Lions TFC","SHONAN Table Football Club","Skien Wildcats","Sociedade Esportiva Palmeiras",
  "Solent Table Soccer & Subbuteo club","South Staff","Sparta Spreeathen 74/82","Spartak des dames",
  "Spartans Larnaca TFC","Spes Livorno","Sport Club Corinthians Paulista","Sport Club do Recife",
  "Sport Vale United","Sporting America TSC","Sporting Clube De Portugal","SPQR MMIX Roma",
  "SS Lazio TFC Roma","ST Sassari","ST Stembert","Stabiae","Stanway Rovers Flickers","STV 97 Hohenlohe",
  "SUB Kaiserau","Subbito Gol Ferrara","Subbuteisti Modena 1982","Subbuteo Casale",
  "Subbuteo Club Almería","Subbuteo Club Basilicata","Subbuteo Club Höpfigheim",
  "Subbuteo Club La Signoria","Subbuteo Club Labronico","Subbutéo Club Marseille","Subbuteo Club Mestre",
  "Subbuteo Club Nara","Subbuteo Club Pavia","Subbuteo Club Pescara","Subbuteo Club Real Montesilvano",
  "Subbuteo Club Reggio Calabria","Subbuteo Club Silvio Piola","Subbuteo Clube de Benfica",
  "Subbuteo Dragons","Subbuteo Grosseto 2018","Subbuteo L'aquila Club","Subbuteo Le Cannet Côte d'Azur",
  "Subbuteo Oslo","Subbuteo Perth","Subbuteo Taranto","Subbutéo Team Gard","Subbuteo Verona 2016",
  "Subbuteo Vomero","Subbuteo.ch","Subbuteoland","Subbuteurs Athens TSC","Surrey Saracens Subbuteo",
  "Swansea","Sydney TFC","Table Football Club Kashiwa Sunrise","Tampa Bay TSC","Team Campania",
  "Templeuve United TSC","TFC Fiorenza","TFC Mattersburg","TFC Rhein-Hessen Wiesbaden",
  "That Retro Place Subbuteo Club","The Andover Subbuteo Club","The Magnet Broadstairs",
  "The Morecambe Bay Subbuteo Club","The Sports Table Football Club of Western Australia",
  "The Tumbleweeds","The Wessex Subbuteo Club","Thessaloniki SC TSC","Thessaloniki United TSC",
  "Tiburones FM","Tigers Lab","TKy'sBeHEAVENESE TFC","Tokyo Crossover Flickers",
  "Tokyo Sparkling Shooters","Tokyo Sunzeol TFC","Torigno Nostro Club","Toronto SC","Toronto SL",
  "Tralee and Munster Subbuteo Club","Trento Subbuteo","TS Napoli Fighters","TSC Black Rose 98 Roma",
  "TSC Falcons Athens","TSC Phoenix","TSC Royal 78 Kaisermühlen","TSC Stella Artois Milano",
  "TSG Rain 1970","TSL Dortmund 61","TSPA White Star","TV Germania Kaiserau",
  "Underdogs Cholargos TSC","Union Subbuteo Prignac-Puylaurens","US Catanzaro Subbuteo","US Huy",
  "US Valponte 1986","USC Wuppertal","Valletta Lions TFC","Valletta SC","Ves Gentes","Virtus Calabria",
  "Virtus Vipers","Viterbese Subbuteo","Walsall TFC","Wamme SC","Washington Tuesday SL",
  "West Coast TSC","West Midlands SC","Western Flickers TFC","Woburn Casuals",
  "Wolverhampton Table Football Club","Woodlands SC","Worthing Fivestar","Yokohama OSC",
  "Yorkshire Phoenix and Dewsbury Moor TFC"
];

function populateClubSelect(selectId) {
  const sel = document.getElementById(selectId);
  if (!sel) return;
  CLUBS.forEach(club => {
    const opt = document.createElement('option');
    opt.value = club;
    opt.textContent = club;
    sel.appendChild(opt);
  });
}
